version: 0.2

phases:
  pre_build:
  # install:
  #   runtime-versions:
  #     nodejs: 16.x
    commands:
      - echo "Installing dependencies..." 
      - npm cache clean --force
      # - npm install --legacy-peer-deps 
      - npm install
  build:
    commands:
      - echo "Building the React app..."
      - npm run build
  post_build:
    commands:
    - echo "Copying build to S3 Bucket..."
    - aws s3 cp --recursive ./build s3://sellangle.com/
    - aws cloudfront create-invalidation --distribution-id EA3O27QS71ZSY --path /\* 
